/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/common/AppHeader.vue')['default']
    MainTemplate: typeof import('./src/components/boilerplate/MainTemplate.vue')['default']
    MobileNavbar: typeof import('./src/components/common/MobileNavbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Temp: typeof import('./src/components/boilerplate/Temp.vue')['default']
    Test: typeof import('./src/components/boilerplate/test.vue')['default']
  }
}
